export enum Routes {
	PROFILE = '/profile',
	PROFILE_ME = '/profile/me',
	PROFILE_ME_ABOUT = '/profile/me/about',
	PROFILE_ME_LISTS = '/profile/me/lists',
	EXPLORE_TOPICS = '/explore-topics',
	SEARCH = '/search',
	SEARCH_POSTS = '/search/posts',
	SEARCH_PEOPLE = '/search/people',
	SEARCH_TAGS = '/search/tags',
	SEARCH_LISTS= '/search/lists',
	NEW_STORY = '/new-story',
	SIGN_IN = '/sign-in',
	SIGN_UP = '/sign-up',
	ROOT = '/',
	TAG = '/tag',
	POSTS = '/posts',
	LISTS = '/lists',
	ABOUT = '/about',
	NOT_FOUND='/not-found',
	TERMS_OF_SERVICE = '/terms-of-service',
	PRIVACY_POLICY = '/privacy-policy',
	FORGOT_PASSWORD = '/forgot-password',
	SETTINGS = '/settings',
	VERIFY_EMAIL = '/verify'
}